compatibility_date = "2024-10-04"
main = "src/index.ts"
minify = true
name = "alist"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
directory = "./dist/"

[[routes]]
pattern = "alist.chaimi.cc/*"
zone_name = "chaimi.cc"

[build]
command = """
wget https://github.com/alist-org/alist-web/releases/latest/download/dist.tar.gz && 
tar -zxvf dist.tar.gz --exclude=dist/static/manifest.json
"""
